ifndef ROLLPY
  ROLLPY = python
endif

ifndef PYVERSION
  PYVERSION = 2.6
endif

NAME           = sdsc-swiftclient_py$(PYVERSION)
VERSION        = 3.4.0
RELEASE        = 0
PKGROOT        = /opt/swiftclient

SRC_SUBDIR     = swiftclient

SOURCE_NAME    = python-swiftclient
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

KEYSTONECLIENT_NAME    = python-keystoneclient
KEYSTONECLIENT_SUFFIX  = tar.gz
KEYSTONECLIENT_VERSION = 3.13.0
KEYSTONECLIENT_PKG     = $(KEYSTONECLIENT_NAME)-$(KEYSTONECLIENT_VERSION).$(KEYSTONECLIENT_SUFFIX)
KEYSTONECLIENT_DIR     = $(KEYSTONECLIENT_PKG:%.$(KEYSTONECLIENT_SUFFIX)=%)

FUTURES_NAME    = futures
FUTURES_SUFFIX  = tar.gz
FUTURES_VERSION = 3.1.1
FUTURES_PKG     = $(FUTURES_NAME)-$(FUTURES_VERSION).$(FUTURES_SUFFIX)
FUTURES_DIR     = $(FUTURES_PKG:%.$(FUTURES_SUFFIX)=%)

REQUESTS_NAME    = requests
REQUESTS_SUFFIX  = tar.gz
REQUESTS_VERSION = 2.8.0
REQUESTS_PKG     = $(REQUESTS_NAME)-$(REQUESTS_VERSION).$(REQUESTS_SUFFIX)
REQUESTS_DIR     = $(REQUESTS_PKG:%.$(REQUESTS_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG) $(KEYSTONECLIENT_PKG) $(FUTURES_PKG) $(REQUESTS_DIR)

RPM.EXTRAS     = AutoReq:No
